/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import LienKet.QLMA_QLBAN;
import LienKet.QLNV_QLHD;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.DatabaseHelper;


/**
 *
 * @author Admin
 */
public class DangNhap extends javax.swing.JFrame {
//    String user1 = "user1";
//    String pass1 = "678";
//    String user2 = "user2";
//    String pass2 = "123";
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        setTitle("Đăng nhập");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("ĐĂNG NHẬP ");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel2.setText("Tên đăng nhập ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setText("Mật khẩu ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 260, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, -1));

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        txtEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/DN.jpg"))); // NOI18N
        txtEmail.setText("jLabel4");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
//        if(checkForm()){
//            String username = txtTenDN.getText();
//            String password = new String(txtPassword.getPassword());
//            if(username.equals(user1) && password.equals(pass1)){
//                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
//                QLMA_QLBAN main = new QLMA_QLBAN();
//                main.setVisible(true);
//                this.dispose();
//                return;
//            }
//            else if (username.equals(user2) && password.equals(pass2)) {
//                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
//                QLNV_QLHD main = new QLNV_QLHD();
//                main.setVisible(true);
//                this.dispose();             
//                return;
//            } 
//            else{
//                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại");
//                return;
//            }
//        }
          DangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
                System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
    public boolean checkForm(){
        String passWord = new String(txtPassword.getPassword());
        if(txtTenDN.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên đăng nhập đang bỏ trống");
            return false;
        }
        if(passWord.equals("")){
            JOptionPane.showMessageDialog(this, "Mật khẩu đang bỏ trống");
            return false;
        }
        return true;       
    }
    public void DangNhap(){
        try {
            String username = txtTenDN.getText();
            String password = new String(txtPassword.getPassword());

            con = DatabaseHelper.getconnecDb();
            st = con.createStatement();
            String sql = "Select * from users where username='" + username + "' and password='" + password + "'";
            rs = st.executeQuery(sql);
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Tài khoản với mật không đúng");
            } else {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                boolean admin=false;
                 while(rs.next())
                 {
                        admin  = rs.getBoolean("admin");
                 }
                 if(admin)
                 {
                     QLMA_QLBAN main = new  QLMA_QLBAN();
                     main.show();
                     //admin 678
                 }else
                 {
                     QLNV_QLHD main = new  QLNV_QLHD();
                     main.show();
                     //user , 123
                 }
                 dispose();
            }
            }catch (Exception e) {
            }    
        } 
    }
        

