package LienKet;

import quanlyquanan.QuanLyBan;
import quanlyquanan.QuanLyMonAn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class QLMA_QLBAN extends javax.swing.JFrame {

    /**
     * Creates new form QLMA_QLBAN
     */
    public QLMA_QLBAN() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQLMA = new javax.swing.JButton();
        btnQLBA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLMA.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnQLMA.setText("Quản lý món ăn ");
        btnQLMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMAActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnQLBA.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnQLBA.setText("Quản lý bàn ăn ");
        btnQLBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLBAActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 340, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/BG_LK.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 620, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLBAActionPerformed
        QuanLyBan main = new QuanLyBan();
        main.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnQLBAActionPerformed

    private void btnQLMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMAActionPerformed
        QuanLyMonAn main = new QuanLyMonAn();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLMAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMA_QLBAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMA_QLBAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMA_QLBAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMA_QLBAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLMA_QLBAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLBA;
    private javax.swing.JButton btnQLMA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
